# Generated by Django 4.2.11 on 2024-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
