# Generated by Django 4.2.11 on 2024-05-01 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0003_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="register_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="building",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
        migrations.AddField(
            model_name="professor",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=20),
        ),
    ]
