# Generated by Django 4.2.11 on 2024-05-01 16:21

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0004_building_register_date_building_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField()),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
