# Generated by Django 4.2.11 on 2024-05-06 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0011_debt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("owed_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(blank=True, default="00", max_length=20)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ucsm_api.debt"
                    ),
                ),
            ],
        ),
    ]
