# Generated by Django 4.2.11 on 2024-05-06 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0015_commission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "final_score",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(20),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "simulated_score",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(20),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ucsm_api.enrollment",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ucsm_api.subject",
                    ),
                ),
            ],
        ),
    ]
