# Generated by Django 4.2.11 on 2024-05-07 02:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ucsm_api", "0018_commission_commission_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(20),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PRIMERA FASE", "First"),
                            ("SEGUNDA FASE", "Second"),
                            ("TERCERA FASE", "Third"),
                        ],
                        default="PRIMERA FASE",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                (
                    "register_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "student_commision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ucsm_api.studentcommission",
                    ),
                ),
            ],
        ),
    ]
